[package]
name = "dr_demo"
version = "0.1.0"
authors = ["a-hacker <austin.hacker@datarobot.com>"]
edition = "2018"

[lib]
name = "dr_demo"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.8.0"
features = ["extension-module"]
